server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysecurity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show_sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUri:
      defaultZone: http://localhost:8761/eureka